{
	'name': 'Documents management',
	'summary': 'Manage your documents with fine grained access management',
	'author': 'Marex Sarl',
	'website': 'marex-sarl.com',
	'version': '17.0.1.0.0',
	'license': 'LGPL-3',
	'category': 'Documents',
	'depends':['base','mail'],
	'data': [
		'security/flexi_documents_security.xml',
		'security/ir.model.access.csv',
		'data/flexi_document_month_data.xml',
		'data/flexi_documents_mail_template.xml',
		'data/cron.xml',
		'views/menu.xml',
		'views/flexi_document_folder_views.xml',
		'views/flexi_document_location_views.xml',
		'views/flexi_document_month_views.xml',
		'views/flexi_document_profile_views.xml',
		'views/flexi_document_year_views.xml',
		'views/flexi_document_content_views.xml',
		'views/res_company.xml',
	],
	'application': True,
	'installable': True,
}
